name: "CI - JDK 11 Build"

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]


jobs:
    build-jdk11:
        name: "JDK 11 Build"
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
            -   name: Setup AdoptOpenJDK
                uses: joschi/setup-jdk@v2.3.0
                with:
                    java-version: 11
            -   name: Build
                run: mvn clean package -X -Dquarkus.test.profile.tags=core

